# The suggested solution groups together in one layer (step) the actions that inject and require the secret with the one that cleans it up. 
# This produces a clean build history.

FROM ruby:2.5.5

ARG PRIVATE_SSH_KEY

RUN echo "${PRIVATE_SSH_KEY}" > /root/.ssh/id_rsa && \
  bundle install && \
  rm /root/.ssh/id_rsa