# docker build . -t spetushkou/expressjs --build-arg="NODE_ENV=production"

version: '3.7'
name: 'expressjs'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: 'spetushkou/expressjs'
    ports:
      - '3000:3000'
    networks:
      - network-default
networks:
  network-default:
