version: '3.7'
name: 'expressjs'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: 'spetushkou/expressjs'
    expose:
      - '3000'
    ports:
      - '3000:3000'
    networks:
      - network-default
networks:
  network-default:
