# docker build . -t my-fancy-image --build-arg PRIVATE_SSH_KEY=xxx
# docker history my-fancy-image
# >  31 seconds ago   RUN |1 PRIVATE_SSH_KEY=xxx /bin/sh -c mkdir …   21.8MB    buildkit.dockerfil

FROM ruby:2.5.5-alpine

# This is a secret
ARG PRIVATE_SSH_KEY

# Just a basic Gemfile to make bundle install happy
RUN echo 'source "https://rubygems.org"; gem "sinatra"' > Gemfile

# We require the secret for installing dependencies
RUN mkdir -p /root/.ssh/ && \
  echo "${PRIVATE_SSH_KEY}" > /root/.ssh/id_rsa && \
  bundle install && \
  rm /root/.ssh/id_rsa

CMD ruby -e "puts 1 + 2"