# When building React applications, you need a Node environment to compile the JavaScript code, 
# SASS stylesheets, and more into static HTML, JavaScript, and CSS. 
# If you aren't doing server-side rendering, you don't even need a Node environment for the production build.
# This example uses a node:20 image to perform the build, which maximizes layer caching, 
# and then copies the output into an nginx container.

FROM node:20-alpine AS build
WORKDIR /app
COPY package* yarn.lock ./
RUN yarn install
COPY public ./public
COPY src ./src
RUN yarn run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html