# see: doc/multi-container-apps.md
version: '3.7'

services:
    app: # The name automatically becomes a network alias
        image: node:20-alpine
        command: sh -c "yarn install && yarn run dev"
        ports:
            - 3000:3000
        working_dir: /app
        volumes:
            - ./:/app # relative paths from the current directory
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: admin
            MYSQL_DB: todos
    mysql:
        platform: linux/x86_64
        image: mysql:5.7
        volumes:
            - todo-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: todos
volumes:
    todo-mysql-data:
