version: '3.7'
name: 'nodejs-dev'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    expose:
      - '3000'
    ports:
      - '3000:3000'
    image: 'spetushkou/nodejs-dev'
    container_name: 'nodejs-dev'
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run start
