# .gitignore
node_modules
dist
out
coverage
.idea
.DS_Store
.env
.env*.local
*.log
*log.csv
*.tsbuildinfo
*.tgz

# docker specific
.husky
.vscode
bin
.*rc.js
.*rc.json
*rc.json
.*config
.*ignore
.dockerignore
Dockerfile*
docker-compose.*
.git
.gitattributes
.gitignore
.npmrc
jest.config.js
TODO
