version: '3.7'
name: 'nodejs'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: 'spetushkou/nodejs'
    expose:
      - '3000'
    ports:
      - '3000:3000'
    networks:
      - network-default
networks:
  network-default:
